export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const SIGN_UP = 'SIGN_UP';
export const UPDATE_USER_APP_SETUP_DETAILS = 'UPDATE_USER_APP_SETUP_DETAILS';
export const APP_SETUP_DONE = 'APP_SETUP_DONE';